complete hw02
Marochkin-Ivan/otus-hw pull request #2
Opened 2024-04-24 12:55 UTC by Marochkin-Ivan

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-04-26 05:14 UTC, dshemin requested changes

2024-04-26 05:14 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +var ErrDigitStart = errors.New("invalid string: can't start with a digit")
Важно:

Поправьте все замечания линтера.

2024-04-26 05:14 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +func unpack(input string) (string, error) {
Критично:

Менять функцию нельзя.

2024-04-26 05:14 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +	err := validate(runes)
Важно:

Избыточная сложность. Мы дважды обходим один и тот же массив, можно сделать за один обход.

2024-04-26 05:14 UTC, dshemin commented on hw02_unpack_string/unpack.go
> +		if runes[i] == '\u005C' {
Важно:

Магическое значение, стоит вынести в константу с понятным именем или оставить пояснительный комментария.

2024-05-03 09:10 UTC, Marochkin-Ivan commented on hw02_unpack_string/unpack.go
> +var ErrDigitStart = errors.New("invalid string: can't start with a digit")
К сожалению, не могу разобрать в чем ошибка:
Running [/home/runner/golangci-lint-1.50.1-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=hw02_unpack_string] in [/home/runner/work/otus-hw/otus-hw/hw02_unpack_string] ...
  Error: File is not `gofumpt`-ed (gofumpt)
  
  Error: issues found
  Ran golangci-lint in 5168ms

2024-05-03 09:13 UTC, Marochkin-Ivan commented on hw02_unpack_string/unpack.go
> +	err := validate(runes)
Подумал, что если сделать все за 1 проход, то код будет плохо читаемым и сложным, поэтому разделил на логические блоки по функциям. А сложность все еще линейная O(n), показалось, что не критично

2024-07-02 16:02 UTC, dshemin approved these changes

2024-07-12 10:49 UTC, merged